language: cpp

  git:
    submodules: true
    quiet: false
    depth: false

compiler: gcc
dist: xenial
cache: ccache

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5

before_script:
  - ls

script:
  - pwd
  - ls


notifications:
  email: false