language: cpp

git:
  submodules: true
  quiet: false
  depth: false

compiler: gcc
dist: xenial
cache: ccache

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5
  - bash scripts/install_dependencies.sh

before_script:
  - pwd

script:
  - pwd
  - cd src/apollo
  - mkdir -p build
  - cd build && cmake ..
  - make -j$(nproc)
  - sudo make install
  - cd /apollo/bin
  - ./spiral_reference_line_smoother_test
  - ./hybrid_a_star_test


# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - g++-4.9
#     - cmake
#     update: true

notifications:
  email: false